# Generated by Django 5.2.3 on 2025-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('about', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('let_about', models.CharField(max_length=100, verbose_name='тема рассылки')),
                ('let_text', models.TextField(verbose_name='текс рассылки')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='имя рассылки')),
                ('mail_time_start', models.DateTimeField(blank=True, null=True, verbose_name='время рассылки начало')),
                ('mail_time_finish', models.DateTimeField(blank=True, null=True, verbose_name='время рассылки конец')),
                ('mail_regularity', models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], max_length=40, verbose_name='регулярность')),
                ('mail_status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], max_length=40, verbose_name='статус рассылки')),
                ('next_time_mailing', models.DateTimeField(blank=True, null=True, verbose_name='следующее время рассылки')),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mails',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки рассылки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('error', 'ошибка')], max_length=20, verbose_name='статус последней попытки рассылки')),
                ('answer', models.CharField(blank=True, max_length=250, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'MailingLog',
                'verbose_name_plural': 'MailingLogs',
            },
        ),
    ]
